#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable

#include "default_parameters.h"

layout(binding = 0, set = 1) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, set = 1, rgba8) uniform image2D RayTraceTarget;

struct RayPayload
{
    vec3 color;
    float distance;
    vec3 normal;
    float reflector;
};

layout(location = 0) rayPayloadEXT RayPayload rayPayload;

void main()
{
    vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    vec2 uv = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
    vec2 ndc = uv * 2.0 - 1.0;
    vec4 origin = ubo.viewInverse * vec4(0.0, 0.0, 0.0, 1.0);
    vec4 target = ubo.projectionInverse * vec4(ndc, 1.0, 1.0);
    vec4 direction = ubo.viewInverse
        * vec4(normalize(target.xyz / target.w), 0.0);

    rayPayload.color = vec3(0.0);
    rayPayload.distance = -1.0;
    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0,
        origin.xyz, 0.001, direction.xyz, 10000.0, 0);
    imageStore(RayTraceTarget, ivec2(gl_LaunchIDEXT.xy),
        vec4(rayPayload.color, 1.0));
}
