#!/usr/bin/env python3
"""Generate the Vanguard-class cruiser mesh used by the HELM // TACTICAL pane.

The ship is lofted from superellipse cross-sections so it has smooth hull
normals, with flat caps for engine exhausts. UV.x encodes a part id that the
fragment shader uses to choose a material:

    0.05  hull plating        0.30  engine exhaust (emissive)
    0.55  nacelle plasma strip 0.80  bridge / window band (emissive)

UV.y runs along the length of each part so the shader can lay out panel
lines and running lights procedurally. Forward is -Z, up is +Y.

Run:  python3 generate_ship.py  (writes ship.obj next to this script)
"""

import math
import os

HULL, ENGINE, PLASMA, WINDOW = 0.05, 0.30, 0.55, 0.80


class Mesh:
    def __init__(self):
        self.v, self.vt, self.vn, self.f = [], [], [], []

    def vert(self, p, uv, n):
        self.v.append(p)
        self.vt.append(uv)
        length = math.sqrt(sum(c * c for c in n)) or 1.0
        self.vn.append(tuple(c / length for c in n))
        return len(self.v)  # OBJ indices are 1-based

    def tri(self, a, b, c):
        self.f.append((a, b, c))

    def quad(self, a, b, c, d):
        self.tri(a, b, c)
        self.tri(a, c, d)

    def write(self, path):
        with open(path, "w", newline="\n") as out:
            out.write("# Vanguard-class cruiser, generated by generate_ship.py\n")
            out.write("o vanguard\n")
            for p in self.v:
                out.write("v %.5f %.5f %.5f\n" % p)
            for t in self.vt:
                out.write("vt %.5f %.5f\n" % t)
            for n in self.vn:
                out.write("vn %.5f %.5f %.5f\n" % n)
            for a, b, c in self.f:
                out.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a, a, a, b, b, b, c, c, c))


def superellipse(theta, rx, ry, power):
    c, s = math.cos(theta), math.sin(theta)
    x = rx * math.copysign(abs(c) ** (2.0 / power), c)
    y = ry * math.copysign(abs(s) ** (2.0 / power), s)
    # Normal of |x/rx|^p + |y/ry|^p = 1.
    nx = math.copysign(abs(c) ** (2.0 - 2.0 / power), c) / rx if c else 0.0
    ny = math.copysign(abs(s) ** (2.0 - 2.0 / power), s) / ry if s else 0.0
    return x, y, nx, ny


def loft(mesh, sections, segments, part, center=(0.0, 0.0), power=2.6,
         cap_front=None, cap_back=None, flip_v=False):
    """sections: list of (z, rx, ry, y_offset). Builds a closed tube."""
    rings = []
    count = len(sections)
    for i, (z, rx, ry, yo) in enumerate(sections):
        v = i / (count - 1)
        ring = []
        # Approximate the longitudinal slope so normals lean along the taper.
        zp, rxp, ryp, _ = sections[max(i - 1, 0)]
        zn, rxn, ryn, _ = sections[min(i + 1, count - 1)]
        dz = (zn - zp) or 1e-4
        drx = (rxn - rxp) / dz
        dry = (ryn - ryp) / dz
        for j in range(segments):
            theta = 2.0 * math.pi * j / segments
            x, y, nx, ny = superellipse(theta, max(rx, 1e-4), max(ry, 1e-4), power)
            slope = -(drx * abs(math.cos(theta)) + dry * abs(math.sin(theta)))
            n = (nx * rx, ny * ry, slope)
            p = (center[0] + x, center[1] + yo + y, z)
            ring.append(mesh.vert(p, (part, 1.0 - v if flip_v else v), n))
        rings.append(ring)
    for i in range(count - 1):
        a, b = rings[i], rings[i + 1]
        for j in range(segments):
            k = (j + 1) % segments
            # Winding chosen so normals face outward when z increases toward the back.
            mesh.quad(a[j], a[k], b[k], b[j])

    def cap(section, facing, cap_part):
        z, rx, ry, yo = section
        mid = mesh.vert((center[0], center[1] + yo, z), (cap_part, 0.5), (0, 0, facing))
        ring = []
        for j in range(segments):
            theta = 2.0 * math.pi * j / segments
            x, y, _, _ = superellipse(theta, max(rx, 1e-4), max(ry, 1e-4), power)
            ring.append(mesh.vert((center[0] + x, center[1] + yo + y, z), (cap_part, 1.0), (0, 0, facing)))
        for j in range(segments):
            k = (j + 1) % segments
            if facing > 0:
                mesh.tri(mid, ring[k], ring[j])
            else:
                mesh.tri(mid, ring[j], ring[k])

    if cap_front:
        cap(sections[0], -1.0, cap_front)
    if cap_back:
        cap(sections[-1], 1.0, cap_back)


def box(mesh, lo, hi, part):
    (x0, y0, z0), (x1, y1, z1) = lo, hi
    faces = [
        ((1, 0, 0), [(x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)]),
        ((-1, 0, 0), [(x0, y0, z1), (x0, y1, z1), (x0, y1, z0), (x0, y0, z0)]),
        ((0, 1, 0), [(x0, y1, z0), (x0, y1, z1), (x1, y1, z1), (x1, y1, z0)]),
        ((0, -1, 0), [(x0, y0, z1), (x0, y0, z0), (x1, y0, z0), (x1, y0, z1)]),
        ((0, 0, 1), [(x1, y0, z1), (x1, y1, z1), (x0, y1, z1), (x0, y0, z1)]),
        ((0, 0, -1), [(x0, y0, z0), (x0, y1, z0), (x1, y1, z0), (x1, y0, z0)]),
    ]
    for n, quad in faces:
        ids = [mesh.vert(p, (part, (p[2] + 2.5) / 5.0), n) for p in quad]
        mesh.quad(*ids)


def wing(mesh, side):
    """A swept, slightly anhedral wing from the hull to a nacelle pylon."""
    root = [(-0.05, -0.02), (1.05, -0.02)]  # z range at the root
    tip = [(0.55, -0.28), (1.15, -0.28)]    # z range at the tip, y droop
    rx, tx = 0.28, 1.20
    t = 0.035
    corners_top = [
        (side * rx, root[0][1] + t, root[0][0]),
        (side * tx, tip[0][1] + t, tip[0][0]),
        (side * tx, tip[1][1] + t, tip[1][0]),
        (side * rx, root[1][1] + t, root[1][0]),
    ]
    corners_bot = [(x, y - 2 * t, z) for (x, y, z) in corners_top]
    up = (side * 0.2, 1.0, 0.0)
    down = (-side * 0.2, -1.0, 0.0)
    top = [mesh.vert(p, (HULL, (p[2] + 2.5) / 5.0), up) for p in corners_top]
    bot = [mesh.vert(p, (HULL, (p[2] + 2.5) / 5.0), down) for p in corners_bot]
    if side > 0:
        mesh.quad(top[0], top[3], top[2], top[1])
        mesh.quad(bot[0], bot[1], bot[2], bot[3])
    else:
        mesh.quad(top[0], top[1], top[2], top[3])
        mesh.quad(bot[0], bot[3], bot[2], bot[1])
    # Leading/trailing/tip edges.
    for i in range(4):
        j = (i + 1) % 4
        a, b = corners_top[i], corners_top[j]
        edge = (b[0] - a[0], 0.0, b[2] - a[2])
        n = (edge[2], 0.0, -edge[0])
        if side < 0:
            n = (-n[0], 0.0, -n[2])
        ids = [mesh.vert(p, (HULL, 0.5), n)
               for p in (corners_top[i], corners_bot[i], corners_bot[j], corners_top[j])]
        if side > 0:
            mesh.quad(ids[0], ids[1], ids[2], ids[3])
        else:
            mesh.quad(ids[0], ids[3], ids[2], ids[1])


def main():
    mesh = Mesh()

    # Main hull: a long needle prow swelling into a broad engineering section.
    hull = []
    for i in range(28):
        s = i / 27.0
        z = -2.4 + s * 4.1
        prow = math.sin(min(s / 0.55, 1.0) * math.pi * 0.5)
        rx = 0.06 + 0.30 * prow + 0.06 * math.sin(s * math.pi)
        ry = 0.03 + 0.16 * prow - 0.03 * max(0.0, s - 0.85) / 0.15
        rx *= 1.0 - 0.18 * max(0.0, s - 0.88) / 0.12
        hull.append((z, rx, ry, 0.02 * math.sin(s * math.pi)))
    loft(mesh, hull, 40, HULL, cap_back=ENGINE, power=2.4)

    # Dorsal spine / bridge module with an emissive window band.
    bridge = []
    for i in range(12):
        s = i / 11.0
        z = -0.55 + s * 1.15
        bump = math.sin(s * math.pi) ** 0.6
        bridge.append((z, 0.03 + 0.13 * bump, 0.02 + 0.09 * bump, 0.17))
    loft(mesh, bridge, 24, HULL, power=2.2)
    band = []
    for i in range(8):
        s = i / 7.0
        z = -0.42 + s * 0.30
        bump = math.sin(s * math.pi) ** 0.5
        band.append((z, 0.02 + 0.105 * bump, 0.02 + 0.06 * bump, 0.20))
    loft(mesh, band, 24, WINDOW, power=2.0)

    # Warp nacelles with a plasma strip along the inboard face.
    for side in (-1.0, 1.0):
        nac = []
        for i in range(22):
            s = i / 21.0
            z = 0.25 + s * 1.65
            nose = math.sin(min(s / 0.18, 1.0) * math.pi * 0.5)
            tail = 1.0 - 0.25 * max(0.0, s - 0.9) / 0.1
            nac.append((z, (0.04 + 0.11 * nose) * tail, (0.04 + 0.10 * nose) * tail, 0.0))
        loft(mesh, nac, 28, HULL, center=(side * 1.25, -0.30), power=2.0, cap_back=ENGINE)
        strip = []
        for i in range(16):
            s = i / 15.0
            z = 0.45 + s * 1.30
            strip.append((z, 0.035, 0.115, 0.0))
        loft(mesh, strip, 12, PLASMA, center=(side * 1.25 - side * 0.09, -0.30), power=2.0)
        # Pylon from the wing tip up into the nacelle.
        box(mesh, (side * 1.25 - 0.02, -0.34, 0.75), (side * 1.25 + 0.02, -0.20, 1.35), HULL)
        wing(mesh, side)

    # Ventral deflector dish housing.
    dish = []
    for i in range(10):
        s = i / 9.0
        z = -0.95 + s * 0.6
        dish.append((z, 0.05 + 0.12 * math.sin(s * math.pi) ** 0.7,
                     0.03 + 0.07 * math.sin(s * math.pi) ** 0.7, -0.15))
    loft(mesh, dish, 20, HULL, power=2.0, cap_front=PLASMA)

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ship.obj")
    mesh.write(out)
    print("wrote %s: %d vertices, %d triangles" % (out, len(mesh.v), len(mesh.f)))


if __name__ == "__main__":
    main()
