#!/usr/bin/env python3
"""Generate the meshes used by the SEASIDE panes.

Rezonality draws one model per pass, has no instancing and gives every model
an identity transform, so animation lives in the vertex shaders. Per-instance
and per-part data is baked into the spare vertex channels instead:

    uv.x      material part id (see the *_PART constants below)
    uv.y      a parameter along the part (height, length, ...)
    color.rgb per-instance data (id, along-body factor, species ...)

Outputs (written next to this script):

    ocean_grid.obj  camera-centred polar grid, displaced by Gerstner waves
                    (also the seabed in the kelp pane)
    sailboat.obj    sloop: hull, deck, cabin, mast, boom, sails, pennant, stays
    lighthouse.obj  banded tower, gallery, lantern, dome and keeper's cottage
    headland.obj    rocky promontory that carries the lighthouse
    kelp.obj        a forest of giant-kelp stipes with blades and bladders
    fish.obj        a school of sardines plus a few garibaldi

Forward is -Z and up is +Y throughout. Run:  python3 generate_models.py
"""

import math
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))


class Mesh:
    def __init__(self, name):
        self.name = name
        self.v, self.c, self.vt, self.vn, self.f = [], [], [], [], []

    def vert(self, p, uv=(0.0, 0.0), n=(0.0, 1.0, 0.0), c=(0.0, 0.0, 0.0)):
        self.v.append(p)
        self.c.append(c)
        self.vt.append(uv)
        length = math.sqrt(sum(x * x for x in n)) or 1.0
        self.vn.append(tuple(x / length for x in n))
        return len(self.v)  # OBJ indices are 1-based

    def tri(self, a, b, c):
        self.f.append((a, b, c))

    def quad(self, a, b, c, d):
        self.tri(a, b, c)
        self.tri(a, c, d)

    def write(self, filename, colors=True, normals=True, uvs=True):
        path = os.path.join(HERE, filename)
        with open(path, "w", newline="\n") as out:
            out.write("# %s, generated by generate_models.py\n" % self.name)
            out.write("o %s\n" % self.name)
            for p, c in zip(self.v, self.c):
                if colors:
                    out.write("v %.4f %.4f %.4f %.4f %.4f %.4f\n" % (p + c))
                else:
                    out.write("v %.4f %.4f %.4f\n" % p)
            if uvs:
                for t in self.vt:
                    out.write("vt %.4f %.4f\n" % t)
            if normals:
                for n in self.vn:
                    out.write("vn %.3f %.3f %.3f\n" % n)
            for a, b, c in self.f:
                if uvs and normals:
                    out.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a, a, a, b, b, b, c, c, c))
                elif normals:
                    out.write("f %d//%d %d//%d %d//%d\n" % (a, a, b, b, c, c))
                else:
                    out.write("f %d %d %d\n" % (a, b, c))
        print("wrote %s: %d vertices, %d triangles" % (filename, len(self.v), len(self.f)))


def norm(v):
    length = math.sqrt(sum(x * x for x in v)) or 1.0
    return tuple(x / length for x in v)


def sub(a, b):
    return tuple(x - y for x, y in zip(a, b))


def add(a, b):
    return tuple(x + y for x, y in zip(a, b))


def scale(a, s):
    return tuple(x * s for x in a)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def lerp(a, b, t):
    return tuple(x + (y - x) * t for x, y in zip(a, b))


def tube(mesh, path, radii, sides, part, color=(0.0, 0.0, 0.0), cap=True, v_range=(0.0, 1.0)):
    """Sweep a circle along a polyline. radii: one radius per path point."""
    count = len(path)
    rings = []
    for i, p in enumerate(path):
        tangent = norm(sub(path[min(i + 1, count - 1)], path[max(i - 1, 0)]))
        ref = (0.0, 1.0, 0.0) if abs(tangent[1]) < 0.9 else (1.0, 0.0, 0.0)
        side = norm(cross(tangent, ref))
        up = cross(side, tangent)
        v = v_range[0] + (v_range[1] - v_range[0]) * i / (count - 1)
        ring = []
        for j in range(sides):
            a = 2.0 * math.pi * j / sides
            n = add(scale(side, math.cos(a)), scale(up, math.sin(a)))
            ring.append(mesh.vert(add(p, scale(n, radii[i])), (part, v), n, color))
        rings.append(ring)
    for i in range(count - 1):
        for j in range(sides):
            k = (j + 1) % sides
            mesh.quad(rings[i][j], rings[i][k], rings[i + 1][k], rings[i + 1][j])
    if cap:
        for end, ring, sign in ((path[-1], rings[-1], 1.0), (path[0], rings[0], -1.0)):
            tangent = norm(sub(path[-1], path[-2])) if sign > 0 else norm(sub(path[0], path[1]))
            mid = mesh.vert(end, (part, v_range[1] if sign > 0 else v_range[0]), tangent, color)
            for j in range(sides):
                k = (j + 1) % sides
                mesh.tri(mid, ring[j], ring[k])


def box(mesh, lo, hi, part, color=(0.0, 0.0, 0.0)):
    (x0, y0, z0), (x1, y1, z1) = lo, hi
    faces = [
        ((1, 0, 0), [(x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)]),
        ((-1, 0, 0), [(x0, y0, z1), (x0, y1, z1), (x0, y1, z0), (x0, y0, z0)]),
        ((0, 1, 0), [(x0, y1, z0), (x0, y1, z1), (x1, y1, z1), (x1, y1, z0)]),
        ((0, -1, 0), [(x0, y0, z1), (x0, y0, z0), (x1, y0, z0), (x1, y0, z1)]),
        ((0, 0, 1), [(x1, y0, z1), (x1, y1, z1), (x0, y1, z1), (x0, y0, z1)]),
        ((0, 0, -1), [(x0, y0, z0), (x0, y1, z0), (x1, y1, z0), (x1, y0, z0)]),
    ]
    for n, quad in faces:
        ids = [mesh.vert(p, (part, (p[1] - y0) / max(y1 - y0, 1e-4)), n, color) for p in quad]
        mesh.quad(*ids)


def lathe(mesh, profile, sides, part, color=(0.0, 0.0, 0.0), center=(0.0, 0.0, 0.0)):
    """Revolve (radius, y) profile points around +Y. uv.y follows the profile."""
    rings = []
    count = len(profile)
    for i, (r, y) in enumerate(profile):
        r0, y0 = profile[max(i - 1, 0)]
        r1, y1 = profile[min(i + 1, count - 1)]
        dr, dy = r1 - r0, y1 - y0
        ring = []
        for j in range(sides + 1):
            a = 2.0 * math.pi * j / sides
            ca, sa = math.cos(a), math.sin(a)
            # Profile normal (dy, -dr) rotated around the axis.
            n = (dy * ca, -dr, dy * sa)
            p = (center[0] + r * ca, center[1] + y, center[2] + r * sa)
            ring.append(mesh.vert(p, (part, i / (count - 1)), n, color))
        rings.append(ring)
    for i in range(count - 1):
        for j in range(sides):
            mesh.quad(rings[i][j], rings[i + 1][j], rings[i + 1][j + 1], rings[i][j + 1])


def sheet(mesh, a, b, c, steps, part, color_fn):
    """Triangular sheet a(tack)-b(head)-c(clew) subdivided for cloth billow.

    color = color_fn(u, v) where u runs along the foot (a->c) and v up (->b).
    """
    n = norm(cross(sub(b, a), sub(c, a)))
    rows = []
    for i in range(steps + 1):
        v = i / steps
        row = []
        for j in range(steps - i + 1):
            u = j / steps
            # Barycentric: a*(1-u-v) + c*u + b*v
            p = tuple(a[k] * (1.0 - u - v) + c[k] * u + b[k] * v for k in range(3))
            row.append(mesh.vert(p, (0.0, v), n, color_fn(u, v)))
        rows.append(row)
    for i in range(steps):
        for j in range(steps - i):
            mesh.tri(rows[i][j], rows[i][j + 1], rows[i + 1][j])
            if j < steps - i - 1:
                mesh.tri(rows[i][j + 1], rows[i + 1][j + 1], rows[i + 1][j])
    # Stamp the part id into uv.x after the fact.
    first = rows[0][0]
    last = rows[-1][-1]
    for index in range(first - 1, last):
        mesh.vt[index] = (part, mesh.vt[index][1])


# ----------------------------------------------------------------------------
# Ocean / seabed grid


def ocean_grid():
    mesh = Mesh("ocean_grid")
    rings, segments = 140, 220
    r0, r_max = 0.3, 1400.0
    k = math.log(r_max / r0) / (rings - 1)
    center = mesh.vert((0.0, 0.0, 0.0))
    ring_ids = []
    for i in range(rings):
        r = r0 * math.exp(k * i)
        ring = []
        for j in range(segments):
            a = 2.0 * math.pi * j / segments
            ring.append(mesh.vert((r * math.cos(a), 0.0, r * math.sin(a))))
        ring_ids.append(ring)
    for j in range(segments):
        jn = (j + 1) % segments
        mesh.tri(center, ring_ids[0][jn], ring_ids[0][j])
    for i in range(rings - 1):
        a, b = ring_ids[i], ring_ids[i + 1]
        for j in range(segments):
            jn = (j + 1) % segments
            mesh.quad(a[j], a[jn], b[jn], b[j])
    mesh.write("ocean_grid.obj", colors=False, normals=False, uvs=False)


# ----------------------------------------------------------------------------
# Sailboat

HULL, DECK, CABIN, SPAR, MAINSAIL, JIB, PENNANT, WINDOW, STAY = (
    0.05, 0.15, 0.25, 0.35, 0.5, 0.6, 0.7, 0.8, 0.9)


def sailboat():
    mesh = Mesh("sailboat")
    length, beam = 8.4, 2.7
    bow_z, stern_z = -length * 0.5, length * 0.5
    stations = 34
    section_pts = 18

    def profile(z):
        t = (z - bow_z) / length  # 0 at bow, 1 at stern
        # Half-beam: fine entry, full aft, transom stern.
        w = beam * 0.5 * (math.sin(min(t * 1.25, 1.0) * math.pi * 0.5) ** 0.75)
        w *= 1.0 - 0.18 * max(t - 0.75, 0.0) / 0.25
        sheer = 0.62 + 0.38 * (1.0 - t) ** 3 + 0.05 * t
        depth = 0.75 * (0.35 + 0.65 * math.sin(min(t * 1.1, 1.0) * math.pi) ** 0.5) * (1.0 - 0.45 * t)
        return max(w, 0.015), sheer, max(depth, 0.08)

    rings = []
    for i in range(stations + 1):
        z = bow_z + length * i / stations
        w, sheer, depth = profile(z)
        ring = []
        for j in range(section_pts + 1):
            th = math.pi * j / section_pts  # 0 = starboard gunwale, pi = port gunwale
            c, s = math.cos(th), math.sin(th)
            x = w * math.copysign(abs(c) ** 0.8, c)
            y = sheer - (sheer + depth) * (s ** 0.7)
            n = (math.copysign(abs(c) ** 1.2, c) / w, -(s ** 1.3) / (sheer + depth) * 0.8, 0.0)
            ring.append((x, y, z, n))
        rings.append(ring)

    hull_ids = []
    for i, ring in enumerate(rings):
        hull_ids.append([mesh.vert(p[:3], (HULL, p[1]), p[3]) for p in ring])
    for i in range(stations):
        for j in range(section_pts):
            mesh.quad(hull_ids[i][j], hull_ids[i + 1][j], hull_ids[i + 1][j + 1], hull_ids[i][j + 1])

    # Transom.
    stern = rings[-1]
    mid = mesh.vert((0.0, stern[0][1] * 0.3, stern_z), (HULL, 0.3), (0.0, 0.0, 1.0))
    ids = [mesh.vert(p[:3], (HULL, p[1]), (0.0, 0.0, 1.0)) for p in stern]
    for j in range(section_pts):
        mesh.tri(mid, ids[j], ids[j + 1])

    # Cambered teak deck between the gunwales.
    for i in range(stations):
        a0, a1 = rings[i][0], rings[i][-1]
        b0, b1 = rings[i + 1][0], rings[i + 1][-1]
        strip = []
        for ring_pts in ((a0, a1), (b0, b1)):
            row = []
            for k in range(5):
                u = k / 4.0
                p = lerp(ring_pts[0][:3], ring_pts[1][:3], u)
                width = abs(ring_pts[0][0]) + 1e-3
                camber = 0.06 * (1.0 - (2.0 * u - 1.0) ** 2) * min(width / 0.6, 1.0)
                row.append(mesh.vert((p[0], p[1] - 0.02 + camber, p[2]), (DECK, u), (0.0, 1.0, 0.0)))
            strip.append(row)
        for k in range(4):
            mesh.quad(strip[0][k], strip[0][k + 1], strip[1][k + 1], strip[1][k])

    # Toe rail along both gunwales.
    for side in (0, -1):
        path = [(r[side][0] * 0.98, r[side][1] + 0.04, r[side][2]) for r in rings]
        tube(mesh, path, [0.035] * len(path), 5, SPAR)

    deck_y = 0.66
    # Cabin trunk with a raked front and glowing ports.
    cabin_lo, cabin_hi = (-0.62, deck_y - 0.05, -0.9), (0.62, deck_y + 0.5, 1.6)
    box(mesh, cabin_lo, cabin_hi, CABIN)
    for z in (-0.4, 0.3, 1.0):
        for x in (0.625, -0.625):
            box(mesh, (x - 0.01, deck_y + 0.2, z - 0.18), (x + 0.01, deck_y + 0.36, z + 0.18), WINDOW)
    # Companionway hatch.
    box(mesh, (-0.35, deck_y + 0.5, 0.4), (0.35, deck_y + 0.58, 1.3), CABIN)
    # Cockpit coaming.
    box(mesh, (-0.85, deck_y - 0.02, 1.9), (0.85, deck_y + 0.22, 3.6), CABIN)

    # Spars. Mast steps through the cabin roof.
    mast_z = -1.15
    mast_top = 10.2
    tube(mesh, [(0.0, deck_y, mast_z), (0.0, mast_top, mast_z)], [0.075, 0.055], 10, SPAR)
    # Spreaders.
    tube(mesh, [(-0.85, 6.2, mast_z), (0.85, 6.2, mast_z)], [0.03, 0.03], 6, SPAR)
    # Boom, swung out to port on a broad reach.
    boom_angle = math.radians(24.0)
    boom_len = 4.2
    boom_y = deck_y + 1.15
    boom_end = (-math.sin(boom_angle) * boom_len, boom_y, mast_z + math.cos(boom_angle) * boom_len)
    tube(mesh, [(0.0, boom_y, mast_z), boom_end], [0.065, 0.05], 8, SPAR)

    # Mainsail: tack at the gooseneck, head at the masthead, clew at the boom end.
    tack = (0.0, boom_y + 0.05, mast_z + 0.06)
    head = (0.0, mast_top - 0.35, mast_z + 0.06)
    clew = (boom_end[0], boom_end[1] + 0.06, boom_end[2])
    sheet(mesh, tack, head, clew, 18, MAINSAIL, lambda u, v: (u, v, 0.0))

    # Jib: head below the masthead, tack at the stem, clew trimmed out to port.
    bow_top = (0.0, profile(bow_z + 0.05)[1] + 0.05, bow_z + 0.15)
    jib_head = (0.0, 8.5, mast_z - 0.12)
    jib_clew = (-1.25, deck_y + 0.75, mast_z + 1.45)
    sheet(mesh, bow_top, jib_head, jib_clew, 16, JIB, lambda u, v: (u, v, 1.0))

    # Standing rigging.
    stays = [
        [(0.0, mast_top - 0.1, mast_z), bow_top],
        [(0.0, mast_top - 0.1, mast_z), (0.0, 1.0, stern_z - 0.1)],
        [(0.0, 6.2, mast_z), (0.85, 6.2, mast_z), (beam * 0.48, deck_y + 0.05, mast_z + 0.2)],
        [(0.0, 6.2, mast_z), (-0.85, 6.2, mast_z), (-beam * 0.48, deck_y + 0.05, mast_z + 0.2)],
        [(0.85, 6.2, mast_z), (0.0, mast_top - 0.3, mast_z)],
        [(-0.85, 6.2, mast_z), (0.0, mast_top - 0.3, mast_z)],
    ]
    for path in stays:
        for p0, p1 in zip(path[:-1], path[1:]):
            tube(mesh, [p0, p1], [0.012, 0.012], 4, STAY, cap=False)
    # Mainsheet from the boom end down to the cockpit.
    tube(mesh, [boom_end, (-0.3, deck_y + 0.25, 2.9)], [0.012, 0.012], 4, STAY, cap=False)

    # Masthead pennant: a long thin triangle strip that flutters in the shader.
    segments = 12
    p_len = 1.1
    for i in range(segments):
        u0, u1 = i / segments, (i + 1) / segments
        h0, h1 = 0.14 * (1.0 - u0), 0.14 * (1.0 - u1)
        y = mast_top + 0.05
        a = mesh.vert((0.0, y, mast_z + u0 * p_len), (PENNANT, u0), (1.0, 0.0, 0.0), (u0, 0.0, 0.0))
        b = mesh.vert((0.0, y + h0, mast_z + u0 * p_len), (PENNANT, u0), (1.0, 0.0, 0.0), (u0, 1.0, 0.0))
        c = mesh.vert((0.0, y + h1 * 0.5 + (h0 - h1) * 0.5, mast_z + u1 * p_len), (PENNANT, u1), (1.0, 0.0, 0.0), (u1, 1.0, 0.0))
        d = mesh.vert((0.0, y + (h0 - h1) * 0.5, mast_z + u1 * p_len), (PENNANT, u1), (1.0, 0.0, 0.0), (u1, 0.0, 0.0))
        mesh.quad(a, d, c, b)

    mesh.write("sailboat.obj")


# ----------------------------------------------------------------------------
# Lighthouse and headland

TOWER, GALLERY, LANTERN, ROOF, LH_WINDOW, DOOR, HOUSE, HOUSE_ROOF, RAIL, ROCK = (
    0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95)


def shoreline_radius(a):
    """Island shoreline radius. Mirrored in night.glsl."""
    return 17.0 + 3.0 * math.sin(3.0 * a + 1.0) + 2.0 * math.sin(5.0 * a + 2.0) + 1.2 * math.sin(9.0 * a + 0.5)


def headland_height(x, z):
    r = math.hypot(x, z)
    a = math.atan2(z, x)
    inside = shoreline_radius(a) - r  # metres inland of the shoreline
    # Steep cliff band, then a rounded crown that peaks at the lighthouse.
    cliff = 1.0 / (1.0 + math.exp(-inside * 1.3))
    crown = max(0.0, 1.0 - (r / 16.0) ** 2)
    h = -2.5 + 9.0 * cliff + 2.2 * crown
    rough = (0.55 * math.sin(x * 0.9 + 1.3) * math.sin(z * 0.7 + 0.4)
             + 0.3 * math.sin(x * 2.1 + z * 1.3) + 0.22 * math.sin(z * 2.7 - x * 0.6 + 2.0)
             + 0.12 * math.sin(x * 4.3 + 0.7) * math.sin(z * 3.9 + 1.1)
             + 0.6 * math.sin(a * 13.0 + 0.4) * math.sin(r * 0.8))
    # Ledges: soft terraces in the cliff band, like stacked basalt.
    cliff_band = cliff * (1.0 - cliff) * 4.0
    h += rough * (0.5 + 1.1 * cliff_band)
    h += 0.6 * math.sin(h * 2.2) * cliff_band
    # Flatten a pad for the lighthouse and cottage.
    pad = math.exp(-((x * x + z * z) / 30.0))
    h = h * (1.0 - pad) + 8.6 * pad
    return h


def headland():
    mesh = Mesh("headland")
    rings, segments = 70, 200
    r_max = 30.0
    grid = []
    for i in range(rings + 1):
        r = r_max * (i / rings) ** 1.15
        row = []
        for j in range(segments):
            a = 2.0 * math.pi * j / segments
            x, z = r * math.cos(a), r * math.sin(a)
            y = headland_height(x, z)
            row.append((x, y, z))
        grid.append(row)

    def normal_at(x, z):
        e = 0.08
        hx = headland_height(x + e, z) - headland_height(x - e, z)
        hz = headland_height(x, z + e) - headland_height(x, z - e)
        return norm((-hx, 2.0 * e, -hz))

    ids = []
    for i, row in enumerate(grid):
        ids.append([mesh.vert(p, (ROCK, p[1]), normal_at(p[0], p[2])) for p in row])
    for i in range(rings):
        for j in range(segments):
            jn = (j + 1) % segments
            mesh.quad(ids[i][j], ids[i + 1][j], ids[i + 1][jn], ids[i][jn])

    # Surf-washed boulders scattered along the shoreline.
    rng = random.Random(7)
    for b in range(26):
        a = rng.uniform(0.0, 2.0 * math.pi)
        r = shoreline_radius(a) + rng.uniform(-0.5, 2.8)
        cx, cz = r * math.cos(a), r * math.sin(a)
        size = rng.uniform(0.6, 1.8)
        boulder(mesh, (cx, -0.4 + size * 0.3, cz), size, rng)
    mesh.write("headland.obj")


def boulder(mesh, center, size, rng):
    lat, lon = 7, 10
    bumps = [(rng.uniform(-1, 1), rng.uniform(-1, 1), rng.uniform(-1, 1)) for _ in range(4)]
    rows = []
    for i in range(lat + 1):
        th = math.pi * i / lat
        row = []
        for j in range(lon):
            ph = 2.0 * math.pi * j / lon
            d = (math.sin(th) * math.cos(ph), math.cos(th), math.sin(th) * math.sin(ph))
            r = size * (1.0 + 0.18 * sum(math.sin(3.0 * (d[0] * b[0] + d[1] * b[1] + d[2] * b[2]) + k)
                                          for k, b in enumerate(bumps)) / 2.0)
            p = (center[0] + d[0] * r * 1.2, center[1] + d[1] * r * 0.75, center[2] + d[2] * r)
            row.append(mesh.vert(p, (ROCK, p[1]), d))
        rows.append(row)
    for i in range(lat):
        for j in range(lon):
            jn = (j + 1) % lon
            mesh.quad(rows[i][j], rows[i + 1][j], rows[i + 1][jn], rows[i][jn])


def lighthouse():
    mesh = Mesh("lighthouse")
    base_y = 8.4
    tower_h = 13.0
    r_base, r_top = 2.0, 1.35
    profile = [(r_base + 0.25, base_y - 0.6), (r_base + 0.25, base_y + 0.4), (r_base, base_y + 0.45)]
    for i in range(1, 21):
        t = i / 20.0
        profile.append((r_base + (r_top - r_base) * t ** 0.9, base_y + 0.45 + tower_h * t))
    lathe(mesh, profile, 40, TOWER)
    top = base_y + 0.45 + tower_h

    # Gallery deck with corbels, plus a railing.
    lathe(mesh, [(r_top - 0.05, top - 0.5), (r_top + 0.75, top - 0.05), (r_top + 0.85, top),
                 (r_top + 0.85, top + 0.18), (0.0, top + 0.18)], 40, GALLERY)
    for ry in (0.55, 1.05):
        lathe(mesh, [(r_top + 0.8, top + ry), (r_top + 0.84, top + ry + 0.025),
                     (r_top + 0.8, top + ry + 0.05), (r_top + 0.76, top + ry + 0.025),
                     (r_top + 0.8, top + ry)], 40, RAIL)
    for k in range(20):
        a = 2.0 * math.pi * k / 20
        x, z = (r_top + 0.8) * math.cos(a), (r_top + 0.8) * math.sin(a)
        tube(mesh, [(x, top + 0.18, z), (x, top + 1.08, z)], [0.022, 0.022], 4, RAIL, cap=False)

    # Lantern room: glazed drum with mullions, a domed roof, vent ball and rod.
    lr = 1.05
    lathe(mesh, [(lr + 0.06, top + 0.18), (lr + 0.06, top + 0.7), (lr, top + 0.72)], 32, GALLERY)
    lathe(mesh, [(lr, top + 0.72), (lr, top + 2.3)], 32, LANTERN)
    for k in range(10):
        a = 2.0 * math.pi * (k + 0.5) / 10
        x, z = (lr + 0.02) * math.cos(a), (lr + 0.02) * math.sin(a)
        tube(mesh, [(x, top + 0.7, z), (x, top + 2.32, z)], [0.035, 0.035], 4, ROOF, cap=False)
    dome = [(lr + 0.22, top + 2.3), (lr + 0.22, top + 2.4)]
    for i in range(1, 11):
        a = (math.pi * 0.5) * i / 10
        dome.append(((lr + 0.15) * math.cos(a), top + 2.4 + 1.0 * math.sin(a)))
    lathe(mesh, dome, 32, ROOF)
    ball = []
    for i in range(9):
        a = -math.pi * 0.5 + math.pi * i / 8
        ball.append((0.22 * math.cos(a) + 1e-3, top + 3.62 + 0.22 * math.sin(a)))
    lathe(mesh, ball, 16, ROOF)
    tube(mesh, [(0.0, top + 3.8, 0.0), (0.0, top + 4.7, 0.0)], [0.025, 0.012], 5, ROOF)

    # Tower door and a column of small windows facing the camera side (-Z/+X).
    door_a = math.radians(-60.0)
    dx, dz = math.cos(door_a), math.sin(door_a)
    for y in (base_y + 4.0, base_y + 7.6, base_y + 11.0):
        r = r_base + (r_top - r_base) * ((y - base_y) / tower_h) + 0.02
        c = (r * dx, y, r * dz)
        tx, tz = -dz, dx
        quad_on_wall(mesh, c, (tx, 0.0, tz), (dx, 0.0, dz), 0.32, 0.55, LH_WINDOW)
    c = ((r_base + 0.27) * dx, base_y + 0.5, (r_base + 0.27) * dz)
    quad_on_wall(mesh, c, (-dz, 0.0, dx), (dx, 0.0, dz), 0.55, 1.0, DOOR, bottom=True)

    # Keeper's cottage with a gabled roof, chimney and lit windows.
    hx, hz = 5.2, 2.6
    lo = (hx - 2.6, base_y - 0.8, hz - 1.7)
    hi = (hx + 2.6, base_y + 2.4, hz + 1.7)
    box(mesh, lo, hi, HOUSE)
    ridge = base_y + 4.0
    eave = hi[1]
    ov = 0.3
    for sz in (-1.0, 1.0):
        zc = hz + sz * (1.7 + ov)
        n = (0.0, 1.6, sz * 1.7)
        a = mesh.vert((lo[0] - ov, eave - 0.2, zc), (HOUSE_ROOF, 0.0), n)
        b = mesh.vert((hi[0] + ov, eave - 0.2, zc), (HOUSE_ROOF, 0.0), n)
        c = mesh.vert((hi[0] + ov, ridge, hz), (HOUSE_ROOF, 1.0), n)
        d = mesh.vert((lo[0] - ov, ridge, hz), (HOUSE_ROOF, 1.0), n)
        mesh.quad(a, b, c, d)
    for sx in (lo[0], hi[0]):
        nx = -1.0 if sx == lo[0] else 1.0
        a = mesh.vert((sx, eave, hz - 1.7), (HOUSE, 1.0), (nx, 0.0, 0.0))
        b = mesh.vert((sx, eave, hz + 1.7), (HOUSE, 1.0), (nx, 0.0, 0.0))
        c = mesh.vert((sx, ridge - 0.15, hz), (HOUSE, 1.0), (nx, 0.0, 0.0))
        mesh.tri(a, b, c)
    box(mesh, (hx + 1.4, ridge - 1.2, hz + 0.3), (hx + 1.9, ridge + 0.7, hz + 0.8), HOUSE)
    for wx in (hx - 1.5, hx, hx + 1.5):
        box(mesh, (wx - 0.32, base_y + 0.55, lo[2] - 0.03), (wx + 0.32, base_y + 1.55, lo[2] + 0.01), LH_WINDOW)
    box(mesh, (lo[0] - 0.03, base_y + 0.55, hz - 0.4), (lo[0] + 0.01, base_y + 1.55, hz + 0.4), LH_WINDOW)

    mesh.write("lighthouse.obj")


def quad_on_wall(mesh, c, tangent, normal, w, h, part, bottom=False):
    y0 = c[1] if bottom else c[1] - h * 0.5
    pts = []
    for su, sv in ((-1, 0), (1, 0), (1, 1), (-1, 1)):
        p = (c[0] + tangent[0] * w * 0.5 * su, y0 + h * sv, c[2] + tangent[2] * w * 0.5 * su)
        pts.append(mesh.vert(p, (part, float(sv)), normal))
    mesh.quad(pts[0], pts[3], pts[2], pts[1])


# ----------------------------------------------------------------------------
# Kelp forest

STIPE, BLADE, BLADDER = 0.1, 0.5, 0.8


def kelp():
    mesh = Mesh("kelp")
    rng = random.Random(11)
    strands = []
    while len(strands) < 64:
        x = rng.uniform(-36.0, 36.0)
        z = rng.uniform(-62.0, 6.0)
        # Keep a clear swim lane in front of the camera.
        if abs(x - 1.0) < 3.5 + max(0.0, z + 20.0) * 0.12 and z > -24.0:
            continue
        if any((x - sx) ** 2 + (z - sz) ** 2 < 7.0 for sx, sz, _ in strands):
            continue
        strands.append((x, z, rng.uniform(14.0, 19.5)))

    for sid, (x, z, height) in enumerate(strands):
        phase = (sid * 0.618034) % 1.0
        segs = 28
        lean = (rng.uniform(-0.8, 0.8), rng.uniform(-0.8, 0.8))
        path = []
        for i in range(segs + 1):
            h = i / segs
            path.append((x + lean[0] * h * h * 2.0 + 0.3 * math.sin(h * 5.0 + sid),
                         -0.3 + height * h,
                         z + lean[1] * h * h * 2.0 + 0.3 * math.cos(h * 4.0 + sid)))
        # Stipe: encode height fraction in color.g per ring via a custom sweep.
        rings = []
        for i, p in enumerate(path):
            h = i / segs
            ring = []
            for j in range(5):
                a = 2.0 * math.pi * j / 5
                n = (math.cos(a), 0.0, math.sin(a))
                q = (p[0] + n[0] * 0.05, p[1], p[2] + n[2] * 0.05)
                ring.append(mesh.vert(q, (STIPE, h), n, (phase, h, 0.0)))
            rings.append(ring)
        for i in range(segs):
            for j in range(5):
                k = (j + 1) % 5
                mesh.quad(rings[i][j], rings[i][k], rings[i + 1][k], rings[i + 1][j])

        # Blades alternate up the stipe, each with a small gas bladder at its base.
        blade_count = int(height * 3.2)
        for b in range(blade_count):
            hb = 0.06 + 0.92 * (b + rng.uniform(0.0, 0.6)) / blade_count
            idx = hb * segs
            i0 = min(int(idx), segs - 1)
            base = lerp(path[i0], path[i0 + 1], idx - i0)
            ang = b * 2.4 + rng.uniform(-0.4, 0.4)
            out = (math.cos(ang), 0.0, math.sin(ang))
            blade_len = rng.uniform(1.3, 2.3) * (1.0 - 0.2 * hb)
            blade_w = rng.uniform(0.17, 0.27)
            droop = rng.uniform(0.25, 0.6)
            steps = 7
            side = (-out[2], 0.0, out[0])
            prev = None
            for s in range(steps + 1):
                u = s / steps
                center = add(add(base, scale(out, 0.12 + blade_len * u)), (0.0, (0.35 - droop * u) * u, 0.0))
                w = blade_w * math.sin(min(u * 1.15, 1.0) * math.pi) ** 0.6 + 0.01
                ruffle = 0.05 * math.sin(u * 19.0 + b)
                left = add(center, scale(side, w + ruffle))
                right = add(center, scale(side, -w + ruffle))
                n = norm(cross(side, (out[0], 0.6 - droop * u * 2.0, out[2])))
                c = (phase, hb, u)
                a = mesh.vert(left, (BLADE, u), n, c)
                d = mesh.vert(right, (BLADE, u), n, c)
                if prev:
                    mesh.quad(prev[0], prev[1], d, a)
                prev = (a, d)
            # Bladder: a tiny diamond.
            bc = add(base, scale(out, 0.09))
            r = 0.055
            pts = [add(bc, (0, r, 0)), add(bc, (0, -r, 0)), add(bc, scale(out, r)),
                   add(bc, scale(out, -r)), add(bc, scale(side, r)), add(bc, scale(side, -r))]
            ids = [mesh.vert(p, (BLADDER, 0.5), sub(p, bc), (phase, hb, 0.0)) for p in pts]
            top, bot, f, bk, l, rr = ids
            for e0, e1 in ((f, l), (l, bk), (bk, rr), (rr, f)):
                mesh.tri(top, e0, e1)
                mesh.tri(bot, e1, e0)

    mesh.write("kelp.obj")


# ----------------------------------------------------------------------------
# Fish school

BODY, FIN = 0.2, 0.6


def fish_body(mesh, fid, species, rng):
    """One fish around the origin, nose toward -Z, length ~1.

    color = (id, along-body 0..1 from nose to tail, species).
    """
    stations = 10
    sides = 8
    if species == 0.0:   # sardine: slender, silver
        width, height = 0.085, 0.13
    else:                # garibaldi: deep, rounded body
        width, height = 0.12, 0.3
    rings = []
    for i in range(stations + 1):
        t = i / stations
        z = -0.5 + 0.82 * t
        env = math.sin(min(t * 1.05, 1.0) * math.pi) ** (0.55 if t < 0.5 else 0.9)
        env = max(env, 0.04)
        ring = []
        for j in range(sides):
            a = 2.0 * math.pi * j / sides
            n = (math.cos(a) / width, math.sin(a) / height, 0.0)
            p = (math.cos(a) * width * env, math.sin(a) * height * env, z)
            ring.append(mesh.vert(p, (BODY, t), n, (fid, t * 0.82, species)))
        rings.append(ring)
    for i in range(stations):
        for j in range(sides):
            k = (j + 1) % sides
            mesh.quad(rings[i][j], rings[i + 1][j], rings[i + 1][k], rings[i][k])
    nose = mesh.vert((0.0, 0.0, -0.53), (BODY, 0.0), (0.0, 0.0, -1.0), (fid, 0.0, species))
    for j in range(sides):
        mesh.tri(nose, rings[0][(j + 1) % sides], rings[0][j])
    # Forked tail fin.
    zt = 0.32
    tail_h = height * (1.1 if species == 0.0 else 0.8)
    a = mesh.vert((0.0, 0.0, zt - 0.04), (FIN, 0.0), (1.0, 0.0, 0.0), (fid, 0.82, species))
    b = mesh.vert((0.0, tail_h, zt + 0.2), (FIN, 1.0), (1.0, 0.0, 0.0), (fid, 1.0, species))
    c = mesh.vert((0.0, 0.02, zt + 0.1), (FIN, 0.6), (1.0, 0.0, 0.0), (fid, 0.95, species))
    d = mesh.vert((0.0, -tail_h, zt + 0.2), (FIN, 1.0), (1.0, 0.0, 0.0), (fid, 1.0, species))
    mesh.tri(a, b, c)
    mesh.tri(a, c, d)
    # Dorsal fin.
    e = mesh.vert((0.0, height * 0.85, -0.12), (FIN, 0.0), (1.0, 0.0, 0.0), (fid, 0.38, species))
    f = mesh.vert((0.0, height * 1.35, 0.0), (FIN, 1.0), (1.0, 0.0, 0.0), (fid, 0.5, species))
    g = mesh.vert((0.0, height * 0.7, 0.12), (FIN, 0.3), (1.0, 0.0, 0.0), (fid, 0.62, species))
    mesh.tri(e, f, g)


def fish():
    mesh = Mesh("fish_school")
    rng = random.Random(5)
    sardines, garibaldi = 220, 7
    total = sardines + garibaldi
    for i in range(total):
        species = 0.0 if i < sardines else 1.0
        fish_body(mesh, (i + 0.5) / total, species, rng)
    mesh.write("fish.obj")


if __name__ == "__main__":
    ocean_grid()
    sailboat()
    headland()
    lighthouse()
    kelp()
    fish()
